Combo_Facility="id:combo_facility"
Tokyo_CURA_Healthcare_Center="Tokyo CURA Healthcare Center"
Hongkong_CURA_Healthcare_Center="Hongkong CURA Healthcare Center"
Seoul_CURA_Healthcare_Center="Seoul CURA Healthcare Center"
checkBox="id:chk_hospotal_readmission"
Healthcare_Program="id:radio_program_medicaid"
visit_date="id:txt_visit_date"
comment="id:txt_comment"
Book_Appointment="id:btn-book-appointment"
Appointment_Title="css:div[class='col-sm-12 text-center'] h2"
